"use client";

import { FormEvent, useState } from "react";

export function ContactForm() {
  const [state, setState] = useState<"idle" | "sending" | "success" | "error">("idle");
  const [message, setMessage] = useState<string>();
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setState("sending"); const formElement = event.currentTarget; const form = new FormData(formElement); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const payload = await response.json().catch(() => null) as { message?: string; error?: string } | null; setMessage(response.ok ? payload?.message : payload?.error); setState(response.ok ? "success" : "error"); if (response.ok) formElement.reset(); } catch { setMessage(undefined); setState("error"); } };
  return <form className="contact-form" onSubmit={submit}><div className="field"><label htmlFor="name">Nama</label><input className="input" id="name" name="name" placeholder="Nama lengkap" required /></div><div className="field"><label htmlFor="email">Email bisnis</label><input className="input" id="email" name="email" type="email" placeholder="nama@bisnis.id" required /></div><div className="field"><label htmlFor="company">Nama bisnis</label><input className="input" id="company" name="company" placeholder="Nama bisnis Anda" /></div><div className="field"><label htmlFor="message">Pesan</label><textarea className="input" id="message" name="message" placeholder="Ceritakan kebutuhan Anda" minLength={20} required /></div><button className="button button--primary" type="submit" disabled={state === "sending"}>{state === "sending" ? "Mengirim..." : "Kirim pesan"}</button>{state === "success" && <p className="form-feedback form-feedback--success" role="status">{message ?? "Pesan Anda tersimpan dan akan ditinjau tim dukungan."}</p>}{state === "error" && <p className="form-feedback form-feedback--error" role="alert">{message ?? "Pesan belum dapat diproses. Periksa isian lalu coba lagi."}</p>}</form>;
}
